# Generated by Django 5.1.2 on 2024-12-14 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMOJI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('U_code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=20, unique=True)),
                ('classname', models.CharField(blank=True, default='Unknown Class', max_length=100, null=True)),
                ('students', models.ManyToManyField(blank=True, related_name='student_classes', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EMOJI_MESSAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.class')),
                ('emoji_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.emoji')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='USER_TO_CAPACITY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(choices=[(1, '学生'), (2, '教师'), (3, '管理员')])),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
